BMS_app/urls.py
from django.conf.urls import url
from BMS_app import views

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='Index'),
    url(r'^listall/$', views.ListAll.as_view(), name='ListAll'),
    url(r'^listall/(?P<pk>\d+)/$', views.PersonDetails.as_view(), name='PersonDetails'),
    url(r'^listall/(?P<pk>\d+)/create/$', views.RelativeCreate.as_view(), name='CreateRelatives'),
    url(r'^create/$', views.CreatePerson.as_view(), name='Create'),
    url(r'^update/(?P<pk>\d+)/$', views.UpdatePerson.as_view(), name='Update'),
    url(r'^update_relative/(?P<pk>\d+)/$', views.UpdateRelative.as_view(), name='UpdateRelative'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeletePerson.as_view(), name='Delete'),
    url(r'^delete_relative/(?P<pk>\d+)/$', views.DeleteRelative.as_view(), name='DeleteRelative'),
    url(r'^about/$', views.About.as_view(), name='About'),
    url(r'^results/$', views.BlogSearchListView.as_view(), name='Result'),




]

BarangayManagementSystem/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from registration.backends.simple.views import RegistrationView


class MyRegistrationView(RegistrationView):
    def get_success_url(self,request, user):
        return '/listall/'


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('BMS_app.urls', namespace='BMS_app')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

templates/about.html
{% extends 'base.html' %}
{% block title_block %}
    About
{% endblock %}
{% block body_block %}
This is the about page
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title_block %} Homepage {% endblock %}</title>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/overrides.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/override.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      {% if user.is_authenticated %}
      {% else %}
            <a class="navbar-brand" href="{% url 'BMS_app:Index' %}">BMS APP</a>
      {% endif %}
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      {% if user.is_authenticated %}
        <li><a href="{% url 'BMS_app:ListAll' %}"> <strong>LIST</strong><span class="sr-only">(current)</span></a></li>
      {% else %}
      {% endif %}

        <li><a href="{% url 'BMS_app:About' %}"><strong>ABOUT</strong></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'auth_logout' %}?next=/">Logout</a></li>
            {% else %}
                <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
      </ul>
        {% if user.is_authenticated %}
        <form class="navbar-form navbar-right" role="search" action="{% url 'BMS_app:Result' %}" method="get" accept-charset="utf-8">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" class="searchfield" id="searchbox" name="q">
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
        {% else %}
        {% endif %}


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block body_block %}

{% endblock %}





</body>
</html>

templates/create.html
{% extends 'base.html' %}
{% block title_block %}
    Create
{% endblock %}
{% load bootstrap3 %}
{% block body_block %}

        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">

        </div>


        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <br>
            <fieldset class="fieldset_border">
                <legend class="fieldset_border"><h3>Sign Up</h3></legend>
                <form action="." method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary btn-lg btn-block" >Register</button>
                    {% endbuttons %}
                </form>
            </fieldset>

        </div>

        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">

        </div>

{% endblock %}

templates/create_relative.html
{% extends 'base.html' %}
{% block title_block %}
    Create Relatives
{% endblock %}
{% load bootstrap3 %}
{% block body_block %}


    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">

    </div>


    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <br>
        <fieldset class="fieldset_border">
            <legend class="fieldset_border"><h3>Sign Up</h3></legend>
            <form action="." method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary btn-lg btn-block" >Register</button>
                {% endbuttons %}
            </form>
        </fieldset>

    </div>

    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">

    </div>


{% endblock %}

templates/delete.html
{% extends 'base.html' %}
{% block title_block %}
    Delete
{% endblock %}
{% load bootstrap3 %}
{% block body_block %}

        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">

        </div>


        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <div class="confirmation-box">
                <h3>Would you like to delete this item?</h3>
                <div>
                    <a href="{% url 'BMS_app:ListAll' %}">
                        <button type="submit" class="btn btn-primary btn-lg btn-block" >No, Please Return Me Back</button>
                    </a>
                    <form action="." method="post">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{% url 'BMS_app:ListAll' %}" />

                        <br>
                        <button type="submit" class="btn btn-danger btn-lg btn-block" >Delete</button>
                    </form>
                </div>
            </div>

            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">

        </div>

{% endblock %}

templates/details.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title_block %} Homepage {% endblock %}</title>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/overrides.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/override.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>

<h2>Family Members</h2>
    <table class="table table-striped table-hover table-condensed table-responsive table-bordered">


        {% if relatives %}
            <thead class="thead-default">
            <tr>
                <th>#</th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Last Name</th>
                <th>Age</th>
                <th>Date of Birth</th>
                <th>Gender</th>
                <th>Relation</th>
                <th>Civil Status</th>
                <th>Address</th>
                <th>Contact</th>
                <th>Email</th>
            </tr>
            </thead>
            <tbody>
            {% for relative in relatives %}
                <tr data-href="{% url 'BMS_app:PersonDetails' pk=relative.id %}" >
                    <th  scope="row"></th>
                    <td>{{ relative.first_name }}</td>
                    <td>{{ relative.middle_name }}</td>
                    <td>{{ relative.last_name }}</td>
                    <td>{{ relative.age }}</td>
                    <td>{{ relative.dob }}</td>
                    <td>{{ relative.gender }}</td>
                    <td>{{ relative.relation }}</td>
                    <td>{{ relative.civil_status }}</td>
                    <td>{{ relative.address }}</td>
                    <td>{{ relative.contact_number }}</td>
                    <td>{{ relative.email }}</td>

                    <td>
                        <a href="{% url 'BMS_app:UpdateRelative' pk=relative.id %}">
                            <button type="button" class="btn btn-primary btn-block">Update</button>
                        </a>
                    </td>

                    <td>
                        <a href="{% url 'BMS_app:DeleteRelative' pk=relative.id %}">
                            <button type="button" class="btn btn-danger btn-block">Delete</button>
                        </a>
                    </td>





                </tr>
            {% endfor %}
        {% else %}
            <h4>Click <a href="{% url 'BMS_app:CreateRelatives' pk=pk_id.pk %}">this</a> to register a family member </h4>
        {% endif %}

        </tbody>
    </table>

    <p>
    <h4><a href="{% url 'BMS_app:ListAll' %}">Go Back</a></h4></p>

</body>
</html>

templates/homepage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title_block %} Homepage {% endblock %}
{% block body_block %}

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Carousel indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <!-- Wrapper for carousel items -->

        <div class="carousel-inner">
            <div class="item active">
                <img src="{% static 'images/slide1.jpg' %}" alt="First Slide">
            </div>
            <div class="item">
                <img src="{% static 'images/slide4.png' %}" alt="Second Slide">
            </div>
            <div class="item">
                <img src="{% static 'images/slide3.jpg' %}" alt="Third Slide">
            </div>
        </div>

        <!-- Carousel controls -->
        <a class="carousel-control left" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
        </a>
        <a class="carousel-control right" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>

    </div>



{% endblock %}

templates/listall.html
{% extends 'base.html' %}
{% block title_block %}ListAll{% endblock %}
{% block body_block %}
    <br>
    <h4><a href="{% url 'BMS_app:Create' %}">Register a Person</a></h4>
    <table class="table table-striped table-hover table-condensed table-responsive table-bordered">
        <thead class="thead-default">
        <tr>
            <th>#</th>
            <th>First Name</th>
            <th>Middle Name</th>
            <th>Last Name</th>
            <th>Age</th>
            <th>Date of Birth</th>
            <th>Gender</th>
            <th>Civil Status</th>
            <th>Address</th>
            <th>Contact</th>
            <th>Email</th>

        </tr>
        </thead>
        <tbody>

        {% for object in object_list %}
            <tr class="clickable-row" data-href="{% url 'BMS_app:PersonDetails' pk=object.id %}"data-target="#PersonModal">
                {#      <tr class="clickable-row" data-href="">#}
                <th  scope="row">{{ object.id }}</th>
                <td>{{ object.first_name }}</td>
                <td>{{ object.middle_name }}</td>
                <td>{{ object.last_name }}</td>
                <td>{{ object.age }}</td>
                <td>{{ object.dob }}</td>
                <td>{{ object.gender }}</td>
                <td>{{ object.civil_status }}</td>
                <td>{{ object.address }}</td>
                <td>{{ object.contact_number }}</td>
                <td>{{ object.email }}</td>
                    <td>
                        <a href="{% url 'BMS_app:Update' pk=object.id %}">
                            <button type="button" class="btn btn-primary btn-block">Update</button>
                        </a>
                    </td>

                    <td>
                        <a href="{% url 'BMS_app:Delete' pk=object.id %}">
                            <button type="button" class="btn btn-danger btn-block">Delete</button>
                        </a>
                    </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/results.html
{% extends 'base.html' %}
{% block title_block %}ListAll{% endblock %}
{% block body_block %}
    <br>
    <table class="table table-striped table-hover table-condensed table-responsive table-bordered">
        <thead class="thead-default">
        <tr>
            <th>#</th>
            <th>First Name</th>
            <th>Middle Name</th>
            <th>Last Name</th>
            <th>Age</th>
            <th>Date of Birth</th>
            <th>Gender</th>
            <th>Civil Status</th>
            <th>Address</th>
            <th>Contact</th>
            <th>Email</th>

        </tr>
        </thead>
        <tbody>

        {% for object in object_list %}
            <tr class="clickable-row" data-href="" data-target="#PersonModal">
                {#      <tr class="clickable-row" data-href="">#}
                <th  scope="row">{{ object.id }}</th>
                <td>{{ object.first_name }}</td>
                <td>{{ object.middle_name }}</td>
                <td>{{ object.last_name }}</td>
                <td>{{ object.age }}</td>
                <td>{{ object.dob }}</td>
                <td>{{ object.gender }}</td>
                <td>{{ object.civil_status }}</td>
                <td>{{ object.address }}</td>
                <td>{{ object.contact_number }}</td>
                <td>{{ object.email }}</td>
                <td>
                    <a href="{% url 'BMS_app:Update' pk=object.id %}">
                        <button type="button" class="btn btn-primary btn-block">Update</button>
                    </a>
                </td>

                <td>
                    <a href="{% url 'BMS_app:Delete' pk=object.id %}">
                        <button type="button" class="btn btn-danger btn-block">Delete</button>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}


templates/update.html
{% extends 'base.html' %}
{% block title_block %}
    Update
{% endblock %}
{% load bootstrap3 %}
{% block body_block %}

        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        </div>

        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <br>
            <fieldset class="fieldset_border">
                <legend class="fieldset_border"><h3>Update</h3></legend>
                <form action="." method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary btn-lg btn-block" >Update</button>
                    {% endbuttons %}
                </form>
            </fieldset>
        </div>

        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        </div>

{% endblock %}

templates/updaterelative.html
{% extends 'base.html' %}
{% block title_block %}
    Update Relative
{% endblock %}
{% load bootstrap3 %}
{% block body_block %}

        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        </div>

        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
            <br>
            <fieldset class="fieldset_border">
                <legend class="fieldset_border"><h3>Update</h3></legend>
                <form action="." method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-primary btn-lg btn-block" >Update</button>
                    {% endbuttons %}
                </form>
            </fieldset>
        </div>

        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        </div>

{% endblock %}